ollyrowe/whittle

README.md
=> docs: update rules and logo

src/components/board/TileGrid.tsx, src/components/tile/Tile.tsx
=> feat: update disabled board styles

public/index.html
=> feat: add meta tags to improve seo

.github/workflows/deploy.yml, .github/workflows/release.yml, .github/workflows/test-answers.yml, .github/workflows/test-unit.yml
This fixes some deprecation warnings that were appearing within the pipeline.
=> ci: update checkout action version

src/components/modals/how-to-play/HowToPlayModal.tsx
=> fix: update how to play instructions

cypress/e2e/yesterdays-game.cy.ts, src/components/modals/yesterday/YesterdayModal.tsx, src/model/game/GameLoader.ts
=> Fix first day issue

public/index.html
=> feat: add google analytics installation script

cypress/e2e/spell-word.cy.ts, cypress/e2e/yesterdays-game.cy.ts, cypress/support/commands.ts, src/@types/mui-styles.d.ts, src/components/modals/how-to-play/HowToPlayModal.tsx, src/components/tile/Tile.tsx, src/hooks/useGame.ts, src/misc/colours.ts, src/misc/theme.ts, src/model/Board.ts, src/model/Container.ts, src/model/Tile.ts, src/model/answers/AnswerParser.ts, src/model/enums/TileState.ts, src/model/game/GameLoader.ts
=> feat: add blue colour to correct theme words

src/@types/mui-styles.d.ts, src/components/appbar/AppBar.tsx, src/components/board/Board.tsx, src/components/rack/Rack.tsx, src/components/tile/Tile.tsx, src/misc/theme.ts
=> feat: improve layout for smaller displays

cypress/e2e/hard-mode.cy.ts, cypress/support/commands.ts, src/hooks/useGame.ts, src/model/Board.ts, src/model/game/GameLoader.ts
=> fix: disable tiles in hard mode for new games

src/components/tile/Tile.tsx, src/hooks/useConditionCount.ts, src/hooks/useConditionTimer.ts
=> fix: fix stacking issue when dropping tiles

src/components/board/GameNumber.tsx
=> fix: update game number to be a h1 tag

cypress/e2e/reset-board.cy.ts, cypress/support/commands.ts, src/components/board/Board.tsx, src/components/board/TileGrid.tsx, src/components/providers/GameProvider.spec.tsx, src/components/providers/GameProvider.tsx, src/components/rack/Rack.tsx, src/components/tile/Tile.tsx, src/hooks/useGame.ts
=> Tile double click action & dragging tiles back to rack

cypress/e2e/hints.cy.ts, cypress/e2e/reset-board.cy.ts, cypress/e2e/settings.cy.ts, cypress/support/commands.ts, cypress/support/types.ts, cypress/support/utils.ts, src/App.tsx, src/Game.spec.tsx, src/Game.tsx, src/components/modals/settings/SettingsModal.tsx, src/components/providers/GameProvider.spec.tsx, src/components/providers/GameProvider.tsx, src/components/providers/NotificationProvider.tsx, src/hooks/useGame.ts, src/hooks/useSettings.ts
=> feat: add win guidance notifications

src/misc/theme.ts
=> fix: update theme info colours

README.md
=> docs: add link to twitter within readme

cypress/e2e/streak.cy.ts, cypress/e2e/yesterdays-game.cy.ts, cypress/fixtures/yesterdays-answer.json, cypress/support/e2e.ts, src/hooks/useGame.ts, src/model/game/GameLoader.ts, src/setupTests.ts
=> feat: update first game start date

src/components/tile/Tile.tsx
=> fix: update tile default draggable state

src/App.tsx, src/Game.tsx, src/components/appbar/AppBar.tsx, src/components/modals/how-to-play/HowToPlayModal.spec.tsx, src/components/modals/how-to-play/HowToPlayModal.tsx, src/components/modals/settings/SettingsModal.spec.tsx, src/components/modals/settings/SettingsModal.tsx, src/components/modals/statistics/StatisticsModal.spec.tsx, src/components/modals/statistics/StatisticsModal.tsx, src/components/modals/yesterday/YesterdayModal.spec.tsx, src/components/modals/yesterday/YesterdayModal.tsx, src/components/providers/GameProvider.spec.tsx, src/components/providers/GameProvider.tsx, src/components/providers/ModalProvider.spec.tsx, src/components/providers/ModalProvider.tsx, src/components/providers/NotificationProvider.spec.tsx, src/hooks/useGame.ts
=> Rework modal state

src/components/modals/statistics/buttons/ShareButton.tsx
=> fix: fix text display issue within image share

cypress/e2e/share.cy.ts, src/Game.tsx, src/components/board/Board.tsx, src/components/board/TileGrid.tsx, src/components/modals/share/ShareModal.spec.tsx, src/components/modals/share/ShareModal.tsx, src/components/modals/statistics/buttons/ShareButton.tsx, src/components/providers/GameProvider.spec.tsx, src/components/providers/GameProvider.tsx, src/components/providers/ModalProvider.tsx, src/components/providers/ShareProvider.tsx, src/hooks/useGame.ts, src/setupTests.ts
=> feat: add option to hide letters from shared board

cypress/e2e/score.cy.ts, cypress/e2e/timer.cy.ts, src/components/modals/statistics/DayCircle.tsx, src/components/modals/statistics/StatisticsModal.tsx, src/components/modals/statistics/StreakCalendar.tsx, src/components/modals/statistics/StreakDisplay.tsx, src/components/modals/statistics/StreakNumber.tsx, src/components/modals/statistics/cards/ScoreCard.spec.tsx, src/components/modals/statistics/cards/ScoreCard.tsx, src/components/modals/statistics/cards/StatisticCard.spec.tsx, src/components/modals/statistics/cards/StatisticCard.tsx, src/components/modals/statistics/cards/TimeCard.spec.tsx, src/components/modals/statistics/cards/TimeCard.tsx, src/components/providers/GameProvider.spec.tsx, src/components/providers/GameProvider.tsx, src/hooks/useConditionTimer.ts, src/hooks/useDocumentEventListener.ts, src/hooks/useGame.ts, src/hooks/useTimer.ts, src/model/game/GameLoader.ts
=> Add game timer

cypress.config.ts, cypress/e2e/share.cy.ts, src/Game.tsx, src/components/board/Board.tsx, src/components/board/ShareBoardButton.spec.tsx, src/components/board/ShareBoardButton.tsx, src/components/providers/ShareProvider.tsx, src/hooks/useGame.ts, src/setupTests.ts
=> Add board share button

cypress/e2e/restricted-mode.cy.ts, cypress/e2e/settings.cy.ts, src/components/modals/settings/SettingsModal.tsx, src/components/providers/GameProvider.spec.tsx, src/components/providers/GameProvider.tsx, src/hooks/useGame.ts, src/hooks/useSettings.ts, src/model/game/GameLoader.ts
=> fix: rename hard mode to restricted mode

public/index.html
=> fix: fix meta tag image for link sharing

src/components/board/SolutionBoard.tsx, src/components/board/TileGrid.tsx
=> fix: fix theme styling in yesterday modal

src/answers/answers.json
Closes #182
Closes #183 
Closes #184
=> feat: add a new set of answers

cypress/e2e/timer.cy.ts, src/components/modals/statistics/StatisticsModal.tsx, src/components/modals/statistics/StreakDisplay.tsx, src/hooks/useStreak.ts
=> fix: rework streak logic to fix erroneous timer display

cypress/e2e/events.cy.ts, src/answers/event-answers.json, src/model/enums/Event.ts, src/model/utils/DateUtils.spec.ts, src/model/utils/DateUtils.ts
=> feat: add christmas eve and nye event answers

package-lock.json, package.json
=> chore: bump html-to-image version to fix warnings

cypress/e2e/reset-board.cy.ts, src/hooks/useGame.ts
=> fix: prevent return tile to rack for disabled board

cypress/e2e/external-links.cy.ts, cypress/support/utils.ts, src/components/modals/settings/SettingsModal.tsx, src/components/modals/statistics/buttons/SupportButton.tsx, src/components/modals/statistics/buttons/TwitterButton.tsx
=> Add link tests

cypress/e2e/events.cy.ts, src/answers/event-answers.json, src/model/enums/Event.ts, src/model/utils/DateUtils.spec.ts, src/model/utils/DateUtils.ts
=> feat: add good friday event theme solution

cypress/e2e/events.cy.ts, src/answers/event-answers.json, src/model/enums/Event.ts, src/model/utils/DateUtils.spec.ts, src/model/utils/DateUtils.ts
=> feat: add star wars day event theme solution

src/answers/answers.json
closes #229 
closes #228 
closes #227
=> feat: add new theme solutions

src/components/board/BoardWrapper.tsx, src/components/board/SolutionBoard.tsx, src/components/modals/score/ScoreModal.tsx
=> fix: fix solution board central alignment issue
